name: Check, Test and Clippy

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo

      - name: Install toolchain
        # hacky way to install rust. Rustup is pre-installed on runners. Calling rustup show will detect the rust-toolchain.toml, and subsequently
        # download the needed toolchain and components.
        run: |
          rustup show

      - name: Check
        run: cargo check --workspace --all-features

      - name: Test
        run: cargo test --workspace

      - name: Lint
        run: cargo clippy --workspace
